# Generated by Django 2.2.19 on 2022-06-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
    ]
